### ISSUE TITLE
Jenkins pipeline step not writing to env

### ISSUE THREAD

**Issue by bjoernHeneka** [jenkinsci/consul-kv-builder-plugin#5]
Within my pipeline i want to get some Data from a consul. For that I try to get them with this plugin. From Log output I can see that the value is correct but it isn't written to a environment. 

When I try to do that without pipeline it works fine.

Here's the code, maybe i did sth. wrong?

``` groovy
node ('consul') {
    stage('Get service node') {

        step([
            $class: 'ConsulKVBuilder', 
            debugMode: 'ENABLED', 
            requestMode: 'READ', 
            envVarKey: 'SERVICE_HOST', 
            keyValue: '', 
            key: 'service/'+params.SERVICE_NAME])

        print env.SERVICE_HOST

    }
}
```

And here the Logoutput from Jenkins:

```
Started by user user
[Pipeline] node
Running on <NODE> in /home/jenkins/workspace/Docker-Consul-Deployments/with-pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Get service node)
[Pipeline] step
Consul READ URL:  http://<CONSUL_URL>:8500/v1/kv/service/lala
Response Headers: 
Content-Type=application/json
X-Consul-Index=10370
X-Consul-Knownleader=true
X-Consul-Lastcontact=0
Date=Fri, 28 Oct 2016 13:18:23 GMT
Content-Length=111
Consul K/V pair:  service/lala=fooooooo
Stored ENV variable (k,v):  SERVICE_HOST=null
Raw content:  [{"LockIndex":0,"Key":"service/lala","Flags":0,"Value":"Zm9vb29vb28=","CreateIndex":10370,"ModifyIndex":10370}]
[Pipeline] echo
null
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by jimmyraywv** [comment]
I will have to look at this.  It looks like a bug.  In the meantime, the wrapper function seems to work fine.  Perhaps you could use the wrapper instead of a step that reads.

```    wrap([$class: 'ConsulKVReadWrapper', reads: [[aclToken: '', apiUri: '', debugMode: 'ENABLED', envKey: 'test_key', hostUrl: '', key: 'test/test-key']]]) {
    // some block
}```

**Comment by jimmyraywv** [comment]
I have fixed this and it will be in the next release; I hope to drop that release tonight.

**Comment by bjoernHeneka** [comment]
Hi @jimmyraywv thx for fast support. Wrapper works fine so far. But need to use the step because i need keys in different stages where they get modified. I'm waiting for your new release.

**Comment by bjoernHeneka** [comment]
@jimmyraywv any idea when your fix will be available?

**Comment by jimmyraywv** [comment]
This is in now.  It will take a while to propagate to the update center JSON:  https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/consul-kv-builder/2.0.13/

**Comment by bjoernHeneka** [comment]
Hey @jimmyraywv,

again thx for the fix. I installed the version manually, but still the problem is existent. With the same Jenkinsfile above i got now the following result:

```

Started by user Björn Heneka
[Pipeline] node
Running on <NODE> in /home/jenkins/workspace/Docker-Consul-Deployments/with-pipeline
[Pipeline] {
    [Pipeline] stage
    [Pipeline] { (Get service node)
        [Pipeline] step
        Consul READ URL:  http://<CONSUL_URL>/v1/kv/service/lala
        Response Headers:
        Content-Type=application/json
        X-Consul-Index=10370
        X-Consul-Knownleader=true
        X-Consul-Lastcontact=0
        Date=Wed, 02 Nov 2016 14:21:33 GMT
        Content-Length=111
        Consul K/V pair:  service/lala=fooooooo
        Stored ENV variable (k,v):  SERVICE_HOST=fooooooo
        Raw content:  [{"LockIndex":0,"Key":"service/lala","Flags":0,"Value":"Zm9vb29vb28=","CreateIndex":10370,"ModifyIndex":10370}]
        [Pipeline] echo
        null
        [Pipeline] }
    [Pipeline] // stage
    [Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

As you can see the Variable seems to be written:
`Stored ENV variable (k,v):  SERVICE_HOST=fooooooo`

But when doing a echo there is a `null`

Again maybe I'm doing sth. wrong and I just don't see it?

**Comment by jimmyraywv** [comment]
So, this seems to be a limitation, maybe by design, of the SimpleBuildStep in a Pipeline.  While this works fine in a Freestyle job, it does not work in Pipeline.  This link (https://groups.google.com/forum/#!topic/jenkinsci-dev/OG03cDc7Gew) makes it look like it may never work that way.

The workaround may be to write a single-value custom step that returns a string, or use the wrapper to set a local var in the node.

```
node('master') {
    TEST_KEY = ''

    wrap([$class: 'ConsulKVReadWrapper', reads: [[aclToken: '', apiUri: '', debugMode: 'ENABLED', envKey: 'test_key', hostUrl: '', key: 'test/test-key']]]) {
        echo env.test_key
        TEST_KEY = env.test_key
    }

    echo TEST_KEY
}
```

or for a global var:

```
import groovy.transform.Field
@Field String TEST_KEY

node('master') {

    wrap([$class: 'ConsulKVReadWrapper', reads: [[aclToken: '', apiUri: '', debugMode: 'ENABLED', envKey: 'test_key', hostUrl: '', key: 'test/test-key']]]) {
        echo env.test_key
        TEST_KEY = env.test_key
    }

    echo TEST_KEY
}

node ('master') {
    echo TEST_KEY
}
```

**Comment by bjoernHeneka** [comment]
Alright. This works fine so far. Thank you so much for support.

**Comment by rudhra13** [comment]
Hi, 

I found out that, according to you, issue has been resolved.
But i am facing the same issue in a freestyle job too.

In my job, i am reading the values from consul using consul kv builder step.
But when i am trying to print the values using execute shell step. I am not able to print the values.
Can you please help me here.

Attaching the logs 
```
Using default API URI:  /v1/kv/
Consul READ URL:  http://<consul url>/v1/kv/test1/test2/test3/key_internal
Response Headers: 
Content-Type=application/json
Vary=Accept-Encoding
X-Consul-Index=2286
X-Consul-Knownleader=true
X-Consul-Lastcontact=0
Date=Tue, 01 Jan 2019 13:52:31 GMT
Consul K/V pair:  test1/test2/test3/key_internal=value_internal_jenkins
Stored ENV variable (k,v):  test=value_internal_jenkins
Raw content:  [{"LockIndex":0,"Key":"test1/test2/test3/key_internal","Flags":0,"Value":"dmFsdWVfaW50ZXJuYWxfamVua2lucw==","CreateIndex":2266,"ModifyIndex":2286}]
[test_consul1] $ /bin/bash -xe /var/folders/k7/3zv2wztj6ys942gvfxtpz7wr0000gn/T/jenkins322123237512924365.sh
+ echo 'value is => '
value is => 
Finished: SUCCESS
```

**Comment by a0s** [comment]
Hi, I am writing from the future (almost 3 years after this was opened). The bug is still here :(

**Comment by jimmyraywv** [comment]
@a0s Wow, that's really funny.  You know what else is really funny?  I don't work with Jenkins anymore.
